## Word Embedding Techniques usung Embedding layer in keras

1. Sentences
2. One Hot Representation--  index from the dictionary
3. one_hot rep--> Embedded layer in keras to form Embedding matrix
4. Embedding matrix

voc_size = 1000,,, what is the size of the dectionary

dimension = 10,, 
Dimensions is how many features you have

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'i am a good boy',
       'i am an AI Engineer',
       'understand the meaning of words',
       'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am an AI Engineer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Vocablary_size
voc_size = 10000

## One_Hot Representation

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
onehot_repr

[[518, 5544, 7526, 8226],
 [518, 5544, 7526, 722],
 [518, 2135, 7526, 278],
 [8902, 5720, 3332, 6073, 5953],
 [8902, 5720, 7225, 1693, 4108],
 [467, 518, 5516, 7526, 7193],
 [3095, 5628, 382, 6073]]

## Word Embadding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

1. length of all sentences most be same for pad_sequences
2. `pre` we have some sentences that have one extra word or less for that we use use `pre` pad_sequence
3. sentance_length is 8.. we can set any number accurding to our sentence
4. our sentence lenght is less than 8 but we still pass 8
5. padding=`pre` will set 0 for extra length.. you can see in the below cell

In [17]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0,  518, 5544, 7526, 8226],
       [   0,    0,    0,    0,  518, 5544, 7526,  722],
       [   0,    0,    0,    0,  518, 2135, 7526,  278],
       [   0,    0,    0, 8902, 5720, 3332, 6073, 5953],
       [   0,    0,    0, 8902, 5720, 7225, 1693, 4108],
       [   0,    0,    0,  467,  518, 5516, 7526, 7193],
       [   0,    0,    0,    0, 3095, 5628,  382, 6073]])

6. Now try padding='`post`'

In [18]:

embedded_docss = pad_sequences(onehot_repr, padding='post', maxlen=sent_length)
embedded_docss

array([[ 518, 5544, 7526, 8226,    0,    0,    0,    0],
       [ 518, 5544, 7526,  722,    0,    0,    0,    0],
       [ 518, 2135, 7526,  278,    0,    0,    0,    0],
       [8902, 5720, 3332, 6073, 5953,    0,    0,    0],
       [8902, 5720, 7225, 1693, 4108,    0,    0,    0],
       [ 467,  518, 5516, 7526, 7193,    0,    0,    0],
       [3095, 5628,  382, 6073,    0,    0,    0,    0]])

* Now pass this to the embedding layer
* for that we need dimension.. let's declare

In [20]:
dim = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('Adam', 'mse') #mse is mean squared error

`mse` is mean squared error

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

array([[[ 0.03337355, -0.03952955, -0.04476814,  0.01191612,
          0.01576343, -0.04389329,  0.00161976,  0.01490266,
         -0.00504564,  0.02511423],
        [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,
          0.01576343, -0.04389329,  0.00161976,  0.01490266,
         -0.00504564,  0.02511423],
        [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,
          0.01576343, -0.04389329,  0.00161976,  0.01490266,
         -0.00504564,  0.02511423],
        [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,
          0.01576343, -0.04389329,  0.00161976,  0.01490266,
         -0.00504564,  0.02511423],
        [ 0.01839378, -0.00185402,  0.04195629, -0.01365079,
         -0.0306224 ,  0.03031887, -0.04955135,  0.04903498,
          0.02774079,  0.01180059],
        [-0.00488085, -0.00766803,  0.01435912,  0.0193227 ,
         -0.00998218, -0.00626572, -0.03423711,  0.04754872,
          0.04090131,  0.00183251],
        [ 0.02970849,  0.0451537 ,  0.03916385,  0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0,  518, 5544, 7526, 8226])

In [26]:
model.predict(embedded_docs)[0]

array([[ 0.03337355, -0.03952955, -0.04476814,  0.01191612,  0.01576343,
        -0.04389329,  0.00161976,  0.01490266, -0.00504564,  0.02511423],
       [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,  0.01576343,
        -0.04389329,  0.00161976,  0.01490266, -0.00504564,  0.02511423],
       [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,  0.01576343,
        -0.04389329,  0.00161976,  0.01490266, -0.00504564,  0.02511423],
       [ 0.03337355, -0.03952955, -0.04476814,  0.01191612,  0.01576343,
        -0.04389329,  0.00161976,  0.01490266, -0.00504564,  0.02511423],
       [ 0.01839378, -0.00185402,  0.04195629, -0.01365079, -0.0306224 ,
         0.03031887, -0.04955135,  0.04903498,  0.02774079,  0.01180059],
       [-0.00488085, -0.00766803,  0.01435912,  0.0193227 , -0.00998218,
        -0.00626572, -0.03423711,  0.04754872,  0.04090131,  0.00183251],
       [ 0.02970849,  0.0451537 ,  0.03916385,  0.04697496,  0.04614117,
        -0.01851814, -0.0201773 , -0.01197015

* You guys can see that one number is converted into 10..
this is because the number will be converted to the dimensions number
like dim = 10 and the number is 0
will be converted 10th times

`so you can see that one number is converted 10 times because the dimensions is 10`

and we declare that sent_length = 8

`so our model create 8 arrays including zeros`

one number is converted 10 times.. because of dimensions
`first 4 arrays's numbers will be same because we have 4 zeros. so our model converted zeros into same numbers`